# Netlify build configuration - Simplified and Final Version

[build]
  # This command is the ONLY instruction Netlify should follow to build the site.
  # 1. `chmod +x build.sh`: Makes the build script executable.
  # 2. `./build.sh`: Runs the script that injects API keys.
  command = "chmod +x build.sh && ./build.sh"

  # The directory to publish after the build command has run.
  publish = "dist"
